[package]

name = "cantal"
description = "The monitoring agent"
license = "MIT"
readme = "README.rst"
keywords = ["monitoring", "statistics"]
homepage = "http://github.com/tailhook/cantal"
version = "0.2.6"
authors = ["paul@colomiets.name"]

[dependencies]
rustc-serialize = "0.3"
cbor = "0.3"
libc = "0.1"
regex = "0.1"
argparse = "0.2"
rand = "0.3"
nix = "0.3"
mime = "*"
httparse = "0.1"
unicase = "1.0"
hyper = "0.6"
num = "0.1"
websocket = "0.12"
byteorder = "0.3"
anymap = "0.11"
fern = "0.3"
log = "0.3"
matches = "0.1"
mio = "0.4"

[dependencies.probor]
git = "git://github.com/tailhook/probor"
features = ["regex_serde"]

[dependencies.cantal_values]
path = "cantal_values"

[dependencies.cantal_history]
path = "cantal_history"

[dependencies.cantal_query]
path = "cantal_query"

[dependencies.time]
version = "0.1"
features = ["rustc-serialize"]

[[bin]]
name = "cantal-agent"
path = "src/agent/main.rs"


