[package]

name = "cantal"
description = "The monitoring agent"
license = "MIT"
readme = "README.rst"
keywords = ["monitoring", "statistics"]
homepage = "http://github.com/tailhook/cantal"
version = "0.1.1"
authors = ["paul@colomiets.name"]

[dependencies]
rustc-serialize = "0.3"
cbor = "0.3"
libc = "0.1"
regex = "0.1"
argparse = "0.2"
rand = "0.3"
nix = "0.3"
mime = "*"
httparse = "0.1"
unicase = "0.1"
hyper = "0.6"
num = "0.1"
websocket = "0.12"
byteorder = "0.3"
anymap = "0.11"
fern = "0.3"
log = "0.3"

[dependencies.mio]
git = "git://github.com/carllerche/mio"

[dependencies.time]
version = "0.1"
features = ["rustc-serialize"]

[lib]
name = "cantal"
path = "src/query/lib.rs"

[[bin]]
name = "cantal"
path = "src/cli/main.rs"

[[bin]]
name = "cantal-agent"
path = "src/agent/main.rs"


