[package]

name = "cantal_history"
description = "The compressed in-memory history storage for cantal statistics"
license = "MIT"
keywords = ["monitoring", "statistics"]
homepage = "http://github.com/tailhook/cantal"
version = "0.1.0"
authors = ["paul@colomiets.name"]

[dependencies]
log = "0.3"
num = "0.1"
rustc-serialize = "0.3"
cbor-codec = { git = "git://github.com/twittner/cbor-codec" }
probor = { git = "git://github.com/tailhook/probor" }
byteorder = "0.3"

[dependencies.cantal_values]
path = "../cantal_values"

[lib]
name = "cantal_history"

